### ISSUE TITLE
how to?

### ISSUE THREAD

**Issue by ghajini** [theseanl/deob#9]
@seanl-adg 
js here
https://player.hulu.com/site/dash/302995-dp/js/dp_player.js

related issue
https://github.com/AdguardTeam/AdguardFilters/issues/5706

**Comment by theseanl** [comment]
Hi, the js file you've linked cannot be 'beautified' further by using tools available in this repository. The script you've linked is just minified well, as you would have seen most of variable names and property names are shortened, and there is no way to recover the original variable names and property names.

What tools in this repository does is deobfuscating some scripts that goes beyond being just minified.

**Comment by theseanl** [comment]
You can use this for mere 'beautification' purposes, paste the script in any of the editor in https://seanl-adg.github.io/deob and press `Ctrl + Shift + B`.
